services:
  cloudflare-incident-monitor:
    build: ./app
    container_name: cloudflare-incident-monitor_container
    volumes:
      - ./app/src/storage:/app/src/storage
      - ./app/src/log:/app/src/log
    restart: unless-stopped